---
  - name: installing nginx
    ansible.builtin.apt: 
      name: nginx
      state: latest
      update_cache: yes
    notify: Aplicando configurações



  - name: Deploy Nginx Configuration from template
    ansible.builtin.template:
      src: nginx_main.conf.j2
      dest: /etc/nginx/sites-available/default
      mode: '0644'
    notify: Aplicando configurações  



